# 1. Explain the overall purpose of the package.


 Numpy’s random number routines produce pseudo random numbers using combinations of a 
 BitGenerator to create sequences and a Generator to use those sequences to sample from 
 different statistical distributions:

BitGenerators: Objects that generate random numbers. These are typically unsigned integer words filled with sequences of either 32 or 64 random bits.
Generators: Objects that transform sequences of random bits from a BitGenerator into sequences of numbers that follow a specific probability distribution (such as uniform, Normal or Binomial) within a specified interval.

# 2. Explain the use of the “Simple random data” and “Permutations” functions.

# Simple random data

In [16]:
import numpy as np
import matplotlib.pyplot as plt
np.random.rand(3,2)

array([[0.69795796, 0.51317682],
       [0.5391719 , 0.14283226],
       [0.91325848, 0.48279304]])

In [20]:
np.random.randn(2, 4,)


array([[ 0.81514279, -0.25734888,  0.7758716 ,  0.4650633 ],
       [ 1.10794406, -2.02128948, -2.06448364,  0.09685338]])

# Permutations

## Shuffle

In [21]:
arr = np.arange(10)

In [22]:
np.random.shuffle(arr)
arr

array([3, 7, 5, 1, 8, 6, 2, 9, 0, 4])

In [23]:
arr = np.arange(9).reshape((3, 3))

In [30]:
arr

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [29]:
np.random.shuffle(arr)
arr

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

## Permutation

If passed an array, it will return a shuffled copy of the array; np.random.shuffle shuffles the array in place.

If passed an integer, it will return a shuffled range i.e. np.random.shuffle(np.arange(n))

In [33]:
np.random.permutation(10)

array([8, 3, 5, 6, 9, 0, 1, 2, 7, 4])

In [34]:
np.random.permutation([1, 4, 9, 12, 15])


array([ 9,  1, 15,  4, 12])

In [35]:
arr = np.arange(9).reshape((3, 3))
np.random.permutation(arr)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])